<?xml version="1.0" encoding="utf-8"?>
<MODEL>
  <SAVED_IN_CULTURE>en-US</SAVED_IN_CULTURE>
  <MODEL_FILE_VERSION>4.1</MODEL_FILE_VERSION>
  <MODEL_VERSION MAJOR="6" MINOR="5" BUILD="13" PATCH="0" />
  <ALL_LANGUAGES />
  <GLOBAL_DATA_KEY>00000000-0000-0000-0000-000000000000</GLOBAL_DATA_KEY>
  <MODEL_INFO>
    <ID>8</ID>
    <CHECKINKEY>00000000-0000-0000-0000-000000000000</CHECKINKEY>
    <QAC>False</QAC>
    <CLASSHIDING>False</CLASSHIDING>
    <SPREADINGGUIDE>False</SPREADINGGUIDE>
    <SUPPORTSRATINGS>False</SUPPORTSRATINGS>
    <DISABLE_ST_PROJECTION>False</DISABLE_ST_PROJECTION>
    <DISABLE_LT_PROJECTION>False</DISABLE_LT_PROJECTION>
    <DISABLE_PEER_COMPARISON>False</DISABLE_PEER_COMPARISON>
    <DISABLE_CONSOLIDATIONS>False</DISABLE_CONSOLIDATIONS>
    <DEFAULTLANG>1</DEFAULTLANG>
    <STMTTYPE_ANNUAL_ID>ANNUAL</STMTTYPE_ANNUAL_ID>
    <STMTTYPE_YEARTODATE_ID>FY-TO-DATE</STMTTYPE_YEARTODATE_ID>
    <LANGUAGES>
      <LANG ID="1" />
    </LANGUAGES>
    <NAMES>
      <NAME ID="1">CONTR</NAME>
    </NAMES>
    <DESCRIPTIONS>
      <DESCRIPTION ID="1">Contractors</DESCRIPTION>
    </DESCRIPTIONS>
  </MODEL_INFO>
  <CURRENCIES />
  <MODEL_ADDINS>
    <MODEL_ADDIN ID="1" NAME="RiskCalc" MAPPED="False" ENABLED="False" TYPE="4" />
    <MODEL_ADDIN ID="2" NAME="Reporting Table" MAPPED="True" ENABLED="True" TYPE="1" />
    <MODEL_ADDIN ID="3" NAME="Batch Reporting Table" MAPPED="True" ENABLED="True" TYPE="3" />
    <MODEL_ADDIN ID="4" NAME="Public EDF" MAPPED="False" ENABLED="False" TYPE="4" />
    <MODEL_ADDIN ID="5" NAME="Batch PFP Export" MAPPED="False" ENABLED="False" TYPE="3" />
    <MODEL_ADDIN ID="6" NAME="HOSP117 New" MAPPED="False" ENABLED="False" TYPE="5" />
    <MODEL_ADDIN ID="7" NAME="PFAAddIn" MAPPED="False" ENABLED="False" TYPE="1" />
    <MODEL_ADDIN ID="8" NAME="PFAAddIn Loans" MAPPED="False" ENABLED="False" TYPE="2" />
    <MODEL_ADDIN ID="9" NAME="PFAAddIn Schedules" MAPPED="False" ENABLED="False" TYPE="2" />
    <MODEL_ADDIN ID="11" NAME="Batch ArchiveRetrieval" MAPPED="False" ENABLED="False" TYPE="3" />
    <MODEL_ADDIN ID="12" NAME="Batch RMA Submission" MAPPED="True" ENABLED="True" TYPE="3" />
    <MODEL_ADDIN ID="13" NAME="BatchRatingsUpdate" MAPPED="False" ENABLED="False" TYPE="3" />
    <MODEL_ADDIN ID="14" NAME="HOSP117 Startup" MAPPED="False" ENABLED="False" TYPE="1" />
    <MODEL_ADDIN ID="20" NAME="Batch Archive" MAPPED="False" ENABLED="False" TYPE="3" />
    <MODEL_ADDIN ID="21" NAME="Entity Copy" MAPPED="True" ENABLED="True" TYPE="3" />
    <MODEL_ADDIN ID="22" NAME="Archive Conversion" MAPPED="False" ENABLED="False" TYPE="3" />
    <MODEL_ADDIN ID="23" NAME="ETL Mapping" MAPPED="False" ENABLED="False" TYPE="1" />
    <MODEL_ADDIN ID="24" NAME="Batch ETL Mapping" MAPPED="True" ENABLED="True" TYPE="3" />
    <MODEL_ADDIN ID="25" NAME="LGD Archive AddIn" MAPPED="False" ENABLED="False" TYPE="1" />
    <MODEL_ADDIN ID="26" NAME="AG Startup" MAPPED="False" ENABLED="False" TYPE="1" />
    <MODEL_ADDIN ID="27" NAME="AG New" MAPPED="False" ENABLED="False" TYPE="5" />
    <MODEL_ADDIN ID="28" NAME="Batch Testing" MAPPED="False" ENABLED="False" TYPE="3" />
  </MODEL_ADDINS>
  <MACRO_GROUPINGS />
  <UNKNOWN_MODEL_PROPERTIES>
    <UNKNOWN_MODEL_PROPERTY ID="StmtStatusApproved"><![CDATA[Reviewed]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="FirmTypeConst"><![CDATA[21]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="HideGlobalConstant"><![CDATA[3,4]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="CustomerStateConst"><![CDATA[44]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="CurrencyConstID"><![CDATA[0]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="DetailedFinancialGroup"><![CDATA[4]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="ConsolidationConstID"><![CDATA[6 ]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="RestatedConstID"><![CDATA[7]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="SaveByStatus"><![CDATA[Completed,Reviewed]]></UNKNOWN_MODEL_PROPERTY>
    <UNKNOWN_MODEL_PROPERTY ID="StatusStmtConst"><![CDATA[5]]></UNKNOWN_MODEL_PROPERTY>
  </UNKNOWN_MODEL_PROPERTIES>
  <MODEL_CONFIG><![CDATA[]]></MODEL_CONFIG>
  <RC_MODELS />
  <GLOBAL_CONSTANTS />
  <STMT_CONSTANTS>
    <STMT_CONSTANT ID="1" HIDDEN="False" READONLY="False" LENGTH="30" REQUIRED="False" DISPLAY="False">
      <STMT_CONST_LABEL ID="1">Audit Method</STMT_CONST_LABEL>
      <STMT_CONST_ATTRIBUTE ID="1">&lt;as&gt;&lt;a id="Unqualif'd" v="Unqualif&amp;apos;d"/&gt;&lt;a id="Qualified" v="Qualified"/&gt;&lt;a id="Reviewed" v="Reviewed"/&gt;&lt;a id="Compiled" v="Compiled"/&gt;&lt;a id="Co. Prep'd" v="Co. Prep&amp;apos;d"/&gt;&lt;a id="Tax Return" v="Tax Return"/&gt;&lt;a id="Projection" v="Projection"/&gt;&lt;a id="" v=""/&gt;&lt;hd v="Unqualif&amp;apos;d"/&gt;&lt;pd v="Projection"/&gt;&lt;/as&gt;</STMT_CONST_ATTRIBUTE>
      <STMT_CONSTANT_MACRO_DESC ID="1">AuditMethod</STMT_CONSTANT_MACRO_DESC>
    </STMT_CONSTANT>
    <STMT_CONSTANT ID="2" HIDDEN="False" READONLY="False" LENGTH="30" REQUIRED="False" DISPLAY="False">
      <STMT_CONST_LABEL ID="1">Accountant</STMT_CONST_LABEL>
      <STMT_CONST_ATTRIBUTE ID="1"></STMT_CONST_ATTRIBUTE>
      <STMT_CONSTANT_MACRO_DESC ID="1">Accountant</STMT_CONSTANT_MACRO_DESC>
    </STMT_CONSTANT>
    <STMT_CONSTANT ID="3" HIDDEN="False" READONLY="False" LENGTH="30" REQUIRED="False" DISPLAY="False">
      <STMT_CONST_LABEL ID="1">Analyst</STMT_CONST_LABEL>
      <STMT_CONST_ATTRIBUTE ID="1"></STMT_CONST_ATTRIBUTE>
      <STMT_CONSTANT_MACRO_DESC ID="1">Analyst</STMT_CONSTANT_MACRO_DESC>
    </STMT_CONSTANT>
    <STMT_CONSTANT ID="4" HIDDEN="False" READONLY="False" LENGTH="30" REQUIRED="False" DISPLAY="False">
      <STMT_CONST_LABEL ID="1">Stmt Type</STMT_CONST_LABEL>
      <STMT_CONST_ATTRIBUTE ID="1">&lt;as&gt;&lt;a id="Annual" v="Annual"/&gt;&lt;a id="Monthly" v="Monthly"/&gt;&lt;a id="Quarterly" v="Quarterly"/&gt;&lt;a id="FY-To-Date" v="FY-To-Date"/&gt;&lt;a id="Rolling Stmt" v="Rolling Stmt"/&gt;&lt;a id="" v=""/&gt;&lt;hd v="Annual"/&gt;&lt;pd v=""/&gt;&lt;rscd v="Rolling Stmt"/&gt;&lt;/as&gt;</STMT_CONST_ATTRIBUTE>
      <STMT_CONSTANT_MACRO_DESC ID="1">StmtType</STMT_CONSTANT_MACRO_DESC>
    </STMT_CONSTANT>
    <STMT_CONSTANT ID="5" HIDDEN="False" READONLY="False" LENGTH="30" REQUIRED="False" DISPLAY="True">
      <STMT_CONST_LABEL ID="1">Status</STMT_CONST_LABEL>
      <STMT_CONST_ATTRIBUTE ID="1">&lt;as&gt;&lt;a id="Draft" v="Draft"/&gt;&lt;a id="Completed" v="Completed"/&gt;&lt;a id="Rework" v="Rework"/&gt;&lt;a id="Reviewed" v="Reviewed"/&gt;&lt;hd v="Draft"/&gt;&lt;pd v="Draft"/&gt;&lt;rscd v="Draft"/&gt;&lt;/as&gt;</STMT_CONST_ATTRIBUTE>
      <STMT_CONSTANT_MACRO_DESC ID="1">StatusStmtConst</STMT_CONSTANT_MACRO_DESC>
    </STMT_CONSTANT>
    <STMT_CONSTANT ID="6" HIDDEN="False" READONLY="False" LENGTH="30" REQUIRED="False" DISPLAY="True">
      <STMT_CONST_LABEL ID="1">Consolidation</STMT_CONST_LABEL>
      <STMT_CONST_ATTRIBUTE ID="1">&lt;as&gt;&lt;a id="Unconsolidated" v="Unconsolidated"/&gt;&lt;a id="Consolidated" v="Consolidated"/&gt;&lt;a id="System Combined" v="System Combined"/&gt;&lt;hd v="Unconsolidated"/&gt;&lt;pd v="Unconsolidated"/&gt;&lt;rscd v="Unconsolidated"/&gt;&lt;/as&gt;</STMT_CONST_ATTRIBUTE>
      <STMT_CONSTANT_MACRO_DESC ID="1">Consolidation</STMT_CONSTANT_MACRO_DESC>
    </STMT_CONSTANT>
    <STMT_CONSTANT ID="7" HIDDEN="False" READONLY="False" LENGTH="30" REQUIRED="False" DISPLAY="True">
      <STMT_CONST_LABEL ID="1">Restated</STMT_CONST_LABEL>
      <STMT_CONST_ATTRIBUTE ID="1">&lt;as&gt;&lt;a id="" v=""/&gt;&lt;a id="Restated" v="Restated"/&gt;&lt;a id="Restated2" v="Restated - 2"/&gt;&lt;a id="Restated3" v="Restated - 3"/&gt;&lt;a id="Restated4" v="Restated - 4"/&gt;&lt;a id="Restated5" v="Restated - 5"/&gt;&lt;hd v=""/&gt;&lt;pd v=""/&gt;&lt;rscd v=""/&gt;&lt;/as&gt;</STMT_CONST_ATTRIBUTE>
      <STMT_CONSTANT_MACRO_DESC ID="1">Restated</STMT_CONSTANT_MACRO_DESC>
    </STMT_CONSTANT>
    <STMT_TYPE_STMT_CONST_ID>4</STMT_TYPE_STMT_CONST_ID>
    <ANALYST_STMT_CONST_ID>3</ANALYST_STMT_CONST_ID>
    <AUDIT_METHOD_STMT_CONST_ID>1</AUDIT_METHOD_STMT_CONST_ID>
  </STMT_CONSTANTS>
  <DIVISIONS>
    <DIVISION ID="A" MAPPED="True">
      <DIVISION_LABEL ID="18">Agriculture, Forestry and Fisheries</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Agriculture, Forestry and Fisheries</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Agriculture, Forestry and Fisheries</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Agriculture, Forestry and Fisheries</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">農業、林業和漁業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">การเกษตรการป่าไม้และการประมง</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Agricultura, silvicultura y pesca</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Agricultura, Silvicultura e Pesca</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Сельское, лесное и рыбное хозяйство</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Agricultura, silvicultura y pesca</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Agricoltura, pesca e silvicoltura</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">חקלאות, יערנות ודיג</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">Tarım, Ormancılık ve Balıkçılık</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Agriculture, sylviculture et pisciculture</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">农业、林业和渔业</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Agriculture, sylviculture et pêche</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Agriculture, Forestry and Fisheries</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Agriculture, Forestry and Fisheries</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="B" MAPPED="True">
      <DIVISION_LABEL ID="18">Mineral Industries</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Mineral Industries</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Mineral Industries</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Mineral Industries</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">礦業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">อุตสาหกรรมแร่</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Minería</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Indústrias Minerais</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Добывающая промышленность</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Minería</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Industrie minerali</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">תעשיות מחצבים</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">Maden Sanayisi</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Industries minières</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">采矿业</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Industries minières</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Mineral Industries</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Mineral Industries</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="C" MAPPED="True">
      <DIVISION_LABEL ID="18">Construction</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Construction</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Construction</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Construction</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">建築業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">การก่อสร้าง</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Construcción</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Construção</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Строительство</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Construcción</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Costruzione</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">בנייה</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">İnşaat</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Construction</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">建筑业</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Bâtiment</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Construction</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Construction</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="D" MAPPED="True">
      <DIVISION_LABEL ID="18">Manufacturing</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Manufacturing</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Manufacturing</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Manufacturing</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">製造業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">การผลิต</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Manufacturación</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Fabricação</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Производство</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Manufacturación</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Produzione</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">ייצור</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">İmalat</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Fabrication</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">制造业</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Fabrication</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Manufacturing</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Manufacturing</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="E" MAPPED="True">
      <DIVISION_LABEL ID="18">Transportation, Communication and Utilities</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Transportation, Communication and Utilities</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Transportation, Communication and Utilities</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Transportation, Communication and Utilities</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">運輸業、通訊業和公用事業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">การคมนาคมและสาธารณูปโภค</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Transporte, comunicación y utilidades</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Transporte, Comunicação e Serviços Públicos</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Транспорт, связь и коммунальное хозяйство</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Transporte, comunicación y utilidades</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Trasporti, comunicazioni e servizi pubblici</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">תובלה, תקשורת ושירותים לציבור</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">Taşımacılık, İletişim ve Altyapı Hizmetleri</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Transport, communications et services publics</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">运输、通信和公用事业</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Transport, communications et services publics</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Transportation, Communication and Utilities</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Transportation, Communication and Utilities</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="F" MAPPED="True">
      <DIVISION_LABEL ID="18">Wholesale Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Wholesale Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Wholesale Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Wholesale Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">批發業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">การค้าส่ง</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Comercio mayorista</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Comércio de Atacado</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Оптовая торговля</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Comercio mayorista</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Commercio all’ingrosso</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">מסחר סיטונאי</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">Toptan Ticaret</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Commerce de gros</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">批发贸易</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Commerce de gros</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Wholesale Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Wholesale Trade</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="G" MAPPED="True">
      <DIVISION_LABEL ID="18">Retail Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Retail Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Retail Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Retail Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">零售業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">การค้าปลีก</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Comercio minorista</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Comércio de Varejo</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Розничная торговля</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Comercio minorista</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Commercio al dettaglio</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">מסחר קימעונאי</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">Perakende Ticaret</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Commerce de détail</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">零售贸易</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Commerce de détail</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Retail Trade</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Retail Trade</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="H" MAPPED="True">
      <DIVISION_LABEL ID="18">Finance, Insurance and Real Estate</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Finance, Insurance and Real Estate</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Finance, Insurance and Real Estate</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Finance, Insurance and Real Estate</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">金融業、保險業和房地產業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">การเงินประกันภัยและอสังหาริมทรัพย์</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Finanzas, seguros e inmobiliarias</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Finanças, Seguros e Imóveis</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Финансы, страхование и недвижимость</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Finanzas, seguros e inmobiliarias</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Assicurazioni, finanze e immobiliare</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">כספים, ביטוח ונדל"ן</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">Finansman, Sigorta ve Gayrımenkul</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Finances, assurances et immobilier</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">金融、保险和房地产</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Finances, assurances et immobilier</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Finance, Insurance and Real Estate</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Finance, Insurance and Real Estate</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="I" MAPPED="True">
      <DIVISION_LABEL ID="18">Services</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Services</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Services</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Services</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">服務業</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">บริการ</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Servicios</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Serviços</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Услуги</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Servicios</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Servizi</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">שירותים</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">Hizmetler</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Services</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">服务业</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Services</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Services</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Services</DIVISION_LABEL>
    </DIVISION>
    <DIVISION ID="Z" MAPPED="True">
      <DIVISION_LABEL ID="18">Public Administration</DIVISION_LABEL>
      <DIVISION_LABEL ID="17">Public Administration</DIVISION_LABEL>
      <DIVISION_LABEL ID="16">Public Administration</DIVISION_LABEL>
      <DIVISION_LABEL ID="15">Public Administration</DIVISION_LABEL>
      <DIVISION_LABEL ID="14">公共系統管理</DIVISION_LABEL>
      <DIVISION_LABEL ID="13">การบริหารรัฐกิจ</DIVISION_LABEL>
      <DIVISION_LABEL ID="12">Administración pública</DIVISION_LABEL>
      <DIVISION_LABEL ID="11">Administração Pública</DIVISION_LABEL>
      <DIVISION_LABEL ID="10">Госуд административные органы</DIVISION_LABEL>
      <DIVISION_LABEL ID="9">Administración pública</DIVISION_LABEL>
      <DIVISION_LABEL ID="8">Pubblica amministrazione</DIVISION_LABEL>
      <DIVISION_LABEL ID="7">מינהל ציבורי</DIVISION_LABEL>
      <DIVISION_LABEL ID="6">Kamu Yönetimi</DIVISION_LABEL>
      <DIVISION_LABEL ID="5">Administration publique</DIVISION_LABEL>
      <DIVISION_LABEL ID="4">公共行政部门</DIVISION_LABEL>
      <DIVISION_LABEL ID="3">Administration publique</DIVISION_LABEL>
      <DIVISION_LABEL ID="2">Public Administration</DIVISION_LABEL>
      <DIVISION_LABEL ID="1">Public Administration</DIVISION_LABEL>
    </DIVISION>
  </DIVISIONS>
  <ENTRY_METHODS />
  <TYPES />
  <FLOWS />
  <CLASSES />
  <CONSTANTS />
  <ACCOUNTS />
  <PROJ_TYPES />
  <PARAMS />
  <NAME_OBJECTS />
  <LITERALS />
  <VALUES />
  <REPORT_TYPES />
  <REPORTS />
  <GROUPS />
  <SUBCONTEXTS />
  <CONTEXTS />
  <SUBTOTALS />
  <SYSTEM_MACROS />
  <MACROS />
  <ASSIGNS />
  <UP_SETTINGS>
    <NUM_ANNUAL_STMTS>0</NUM_ANNUAL_STMTS>
    <NUM_INTERIM_STMTS>0</NUM_INTERIM_STMTS>
    <NUM_COMBINED_STMTS>0</NUM_COMBINED_STMTS>
    <NUM_LTP_STMTS>0</NUM_LTP_STMTS>
    <NUM_STP_STMTS>0</NUM_STP_STMTS>
    <NUM_COMBINED_PROJ_STMTS>0</NUM_COMBINED_PROJ_STMTS>
    <UP_ROUNDING>0</UP_ROUNDING>
    <UP_USE_HIDDEN_STMTS>False</UP_USE_HIDDEN_STMTS>
    <UP_INCLUDE_RC>False</UP_INCLUDE_RC>
    <UP_FORCE_RECALC>False</UP_FORCE_RECALC>
    <UP_RUNIFRCFAIL>False</UP_RUNIFRCFAIL>
    <UP_DELETEONFAILURE>False</UP_DELETEONFAILURE>
    <UP_INCLUDEPEERANALYSIS>False</UP_INCLUDEPEERANALYSIS>
    <UP_RUNONSAVE>False</UP_RUNONSAVE>
  </UP_SETTINGS>
  <UP_CONDITIONS />
  <UP_KEYS />
  <UP_MAPPINGS />
  <INDUSTRY_CLASSIFICATION_SYSTEMS />
  <SENSITIVITY_PARAMETERS>
    <SENSITIVITY_PARAMETER ID="1" PARAM_ID="1" DIVISION_ID="A" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="2" PARAM_ID="1" DIVISION_ID="B" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="3" PARAM_ID="1" DIVISION_ID="C" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="4" PARAM_ID="1" DIVISION_ID="D" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="5" PARAM_ID="1" DIVISION_ID="E" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="6" PARAM_ID="1" DIVISION_ID="F" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="7" PARAM_ID="1" DIVISION_ID="G" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="8" PARAM_ID="1" DIVISION_ID="H" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="9" PARAM_ID="1" DIVISION_ID="I" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="10" PARAM_ID="1" DIVISION_ID="Z" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="11" PARAM_ID="2" DIVISION_ID="A" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="12" PARAM_ID="2" DIVISION_ID="B" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="13" PARAM_ID="2" DIVISION_ID="C" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="14" PARAM_ID="2" DIVISION_ID="D" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="15" PARAM_ID="2" DIVISION_ID="E" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="16" PARAM_ID="2" DIVISION_ID="F" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="17" PARAM_ID="2" DIVISION_ID="G" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="18" PARAM_ID="2" DIVISION_ID="H" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="19" PARAM_ID="2" DIVISION_ID="I" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="20" PARAM_ID="2" DIVISION_ID="Z" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="21" PARAM_ID="3" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="22" PARAM_ID="3" DIVISION_ID="B" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="23" PARAM_ID="3" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="24" PARAM_ID="3" DIVISION_ID="D" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="25" PARAM_ID="3" DIVISION_ID="E" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="26" PARAM_ID="3" DIVISION_ID="F" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="27" PARAM_ID="3" DIVISION_ID="G" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="28" PARAM_ID="3" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="29" PARAM_ID="3" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="30" PARAM_ID="3" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="31" PARAM_ID="4" DIVISION_ID="A" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="32" PARAM_ID="4" DIVISION_ID="B" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="33" PARAM_ID="4" DIVISION_ID="C" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="34" PARAM_ID="4" DIVISION_ID="D" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="35" PARAM_ID="4" DIVISION_ID="E" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="36" PARAM_ID="4" DIVISION_ID="F" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="37" PARAM_ID="4" DIVISION_ID="G" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="38" PARAM_ID="4" DIVISION_ID="H" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="39" PARAM_ID="4" DIVISION_ID="I" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="40" PARAM_ID="4" DIVISION_ID="Z" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="41" PARAM_ID="5" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="42" PARAM_ID="5" DIVISION_ID="B" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="43" PARAM_ID="5" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="44" PARAM_ID="5" DIVISION_ID="D" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="45" PARAM_ID="5" DIVISION_ID="E" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="46" PARAM_ID="5" DIVISION_ID="F" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="47" PARAM_ID="5" DIVISION_ID="G" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="48" PARAM_ID="5" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="49" PARAM_ID="5" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="50" PARAM_ID="5" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="51" PARAM_ID="6" DIVISION_ID="A" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="52" PARAM_ID="6" DIVISION_ID="B" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="53" PARAM_ID="6" DIVISION_ID="C" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="54" PARAM_ID="6" DIVISION_ID="D" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="55" PARAM_ID="6" DIVISION_ID="E" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="56" PARAM_ID="6" DIVISION_ID="F" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="57" PARAM_ID="6" DIVISION_ID="G" VALUE="2.5" />
    <SENSITIVITY_PARAMETER ID="58" PARAM_ID="6" DIVISION_ID="H" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="59" PARAM_ID="6" DIVISION_ID="I" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="60" PARAM_ID="6" DIVISION_ID="Z" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="61" PARAM_ID="7" DIVISION_ID="A" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="62" PARAM_ID="7" DIVISION_ID="B" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="63" PARAM_ID="7" DIVISION_ID="C" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="64" PARAM_ID="7" DIVISION_ID="D" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="65" PARAM_ID="7" DIVISION_ID="E" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="66" PARAM_ID="7" DIVISION_ID="F" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="67" PARAM_ID="7" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="68" PARAM_ID="7" DIVISION_ID="H" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="69" PARAM_ID="7" DIVISION_ID="I" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="70" PARAM_ID="7" DIVISION_ID="Z" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="71" PARAM_ID="8" DIVISION_ID="A" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="72" PARAM_ID="8" DIVISION_ID="B" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="73" PARAM_ID="8" DIVISION_ID="C" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="74" PARAM_ID="8" DIVISION_ID="D" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="75" PARAM_ID="8" DIVISION_ID="E" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="76" PARAM_ID="8" DIVISION_ID="F" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="77" PARAM_ID="8" DIVISION_ID="G" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="78" PARAM_ID="8" DIVISION_ID="H" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="79" PARAM_ID="8" DIVISION_ID="I" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="80" PARAM_ID="8" DIVISION_ID="Z" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="81" PARAM_ID="9" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="82" PARAM_ID="9" DIVISION_ID="B" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="83" PARAM_ID="9" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="84" PARAM_ID="9" DIVISION_ID="D" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="85" PARAM_ID="9" DIVISION_ID="E" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="86" PARAM_ID="9" DIVISION_ID="F" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="87" PARAM_ID="9" DIVISION_ID="G" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="88" PARAM_ID="9" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="89" PARAM_ID="9" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="90" PARAM_ID="9" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="91" PARAM_ID="10" DIVISION_ID="A" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="92" PARAM_ID="10" DIVISION_ID="B" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="93" PARAM_ID="10" DIVISION_ID="C" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="94" PARAM_ID="10" DIVISION_ID="D" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="95" PARAM_ID="10" DIVISION_ID="E" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="96" PARAM_ID="10" DIVISION_ID="F" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="97" PARAM_ID="10" DIVISION_ID="G" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="98" PARAM_ID="10" DIVISION_ID="H" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="99" PARAM_ID="10" DIVISION_ID="I" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="100" PARAM_ID="10" DIVISION_ID="Z" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="101" PARAM_ID="11" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="102" PARAM_ID="11" DIVISION_ID="B" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="103" PARAM_ID="11" DIVISION_ID="C" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="104" PARAM_ID="11" DIVISION_ID="D" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="105" PARAM_ID="11" DIVISION_ID="E" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="106" PARAM_ID="11" DIVISION_ID="F" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="107" PARAM_ID="11" DIVISION_ID="G" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="108" PARAM_ID="11" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="109" PARAM_ID="11" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="110" PARAM_ID="11" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="111" PARAM_ID="12" DIVISION_ID="A" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="112" PARAM_ID="12" DIVISION_ID="B" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="113" PARAM_ID="12" DIVISION_ID="C" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="114" PARAM_ID="12" DIVISION_ID="D" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="115" PARAM_ID="12" DIVISION_ID="E" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="116" PARAM_ID="12" DIVISION_ID="F" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="117" PARAM_ID="12" DIVISION_ID="G" VALUE="8" />
    <SENSITIVITY_PARAMETER ID="118" PARAM_ID="12" DIVISION_ID="H" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="119" PARAM_ID="12" DIVISION_ID="I" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="120" PARAM_ID="12" DIVISION_ID="Z" VALUE="5" />
    <SENSITIVITY_PARAMETER ID="121" PARAM_ID="13" DIVISION_ID="A" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="122" PARAM_ID="13" DIVISION_ID="B" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="123" PARAM_ID="13" DIVISION_ID="C" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="124" PARAM_ID="13" DIVISION_ID="D" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="125" PARAM_ID="13" DIVISION_ID="E" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="126" PARAM_ID="13" DIVISION_ID="F" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="127" PARAM_ID="13" DIVISION_ID="G" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="128" PARAM_ID="13" DIVISION_ID="H" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="129" PARAM_ID="13" DIVISION_ID="I" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="130" PARAM_ID="13" DIVISION_ID="Z" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="131" PARAM_ID="14" DIVISION_ID="A" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="132" PARAM_ID="14" DIVISION_ID="B" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="133" PARAM_ID="14" DIVISION_ID="C" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="134" PARAM_ID="14" DIVISION_ID="D" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="135" PARAM_ID="14" DIVISION_ID="E" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="136" PARAM_ID="14" DIVISION_ID="F" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="137" PARAM_ID="14" DIVISION_ID="G" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="138" PARAM_ID="14" DIVISION_ID="H" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="139" PARAM_ID="14" DIVISION_ID="I" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="140" PARAM_ID="14" DIVISION_ID="Z" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="141" PARAM_ID="15" DIVISION_ID="A" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="142" PARAM_ID="15" DIVISION_ID="B" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="143" PARAM_ID="15" DIVISION_ID="C" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="144" PARAM_ID="15" DIVISION_ID="D" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="145" PARAM_ID="15" DIVISION_ID="E" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="146" PARAM_ID="15" DIVISION_ID="F" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="147" PARAM_ID="15" DIVISION_ID="G" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="148" PARAM_ID="15" DIVISION_ID="H" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="149" PARAM_ID="15" DIVISION_ID="I" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="150" PARAM_ID="15" DIVISION_ID="Z" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="151" PARAM_ID="16" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="152" PARAM_ID="16" DIVISION_ID="B" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="153" PARAM_ID="16" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="154" PARAM_ID="16" DIVISION_ID="D" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="155" PARAM_ID="16" DIVISION_ID="E" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="156" PARAM_ID="16" DIVISION_ID="F" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="157" PARAM_ID="16" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="158" PARAM_ID="16" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="159" PARAM_ID="16" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="160" PARAM_ID="16" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="161" PARAM_ID="17" DIVISION_ID="A" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="162" PARAM_ID="17" DIVISION_ID="B" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="163" PARAM_ID="17" DIVISION_ID="C" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="164" PARAM_ID="17" DIVISION_ID="D" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="165" PARAM_ID="17" DIVISION_ID="E" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="166" PARAM_ID="17" DIVISION_ID="F" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="167" PARAM_ID="17" DIVISION_ID="G" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="168" PARAM_ID="17" DIVISION_ID="H" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="169" PARAM_ID="17" DIVISION_ID="I" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="170" PARAM_ID="17" DIVISION_ID="Z" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="171" PARAM_ID="18" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="172" PARAM_ID="18" DIVISION_ID="B" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="173" PARAM_ID="18" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="174" PARAM_ID="18" DIVISION_ID="D" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="175" PARAM_ID="18" DIVISION_ID="E" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="176" PARAM_ID="18" DIVISION_ID="F" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="177" PARAM_ID="18" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="178" PARAM_ID="18" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="179" PARAM_ID="18" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="180" PARAM_ID="18" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="181" PARAM_ID="19" DIVISION_ID="A" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="182" PARAM_ID="19" DIVISION_ID="B" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="183" PARAM_ID="19" DIVISION_ID="C" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="184" PARAM_ID="19" DIVISION_ID="D" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="185" PARAM_ID="19" DIVISION_ID="E" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="186" PARAM_ID="19" DIVISION_ID="F" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="187" PARAM_ID="19" DIVISION_ID="G" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="188" PARAM_ID="19" DIVISION_ID="H" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="189" PARAM_ID="19" DIVISION_ID="I" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="190" PARAM_ID="19" DIVISION_ID="Z" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="191" PARAM_ID="20" DIVISION_ID="A" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="192" PARAM_ID="20" DIVISION_ID="B" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="193" PARAM_ID="20" DIVISION_ID="C" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="194" PARAM_ID="20" DIVISION_ID="D" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="195" PARAM_ID="20" DIVISION_ID="E" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="196" PARAM_ID="20" DIVISION_ID="F" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="197" PARAM_ID="20" DIVISION_ID="G" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="198" PARAM_ID="20" DIVISION_ID="H" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="199" PARAM_ID="20" DIVISION_ID="I" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="200" PARAM_ID="20" DIVISION_ID="Z" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="201" PARAM_ID="21" DIVISION_ID="A" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="202" PARAM_ID="21" DIVISION_ID="B" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="203" PARAM_ID="21" DIVISION_ID="C" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="204" PARAM_ID="21" DIVISION_ID="D" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="205" PARAM_ID="21" DIVISION_ID="E" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="206" PARAM_ID="21" DIVISION_ID="F" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="207" PARAM_ID="21" DIVISION_ID="G" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="208" PARAM_ID="21" DIVISION_ID="H" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="209" PARAM_ID="21" DIVISION_ID="I" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="210" PARAM_ID="21" DIVISION_ID="Z" VALUE="0.15" />
    <SENSITIVITY_PARAMETER ID="211" PARAM_ID="22" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="212" PARAM_ID="22" DIVISION_ID="B" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="213" PARAM_ID="22" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="214" PARAM_ID="22" DIVISION_ID="D" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="215" PARAM_ID="22" DIVISION_ID="E" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="216" PARAM_ID="22" DIVISION_ID="F" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="217" PARAM_ID="22" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="218" PARAM_ID="22" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="219" PARAM_ID="22" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="220" PARAM_ID="22" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="221" PARAM_ID="23" DIVISION_ID="A" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="222" PARAM_ID="23" DIVISION_ID="B" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="223" PARAM_ID="23" DIVISION_ID="C" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="224" PARAM_ID="23" DIVISION_ID="D" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="225" PARAM_ID="23" DIVISION_ID="E" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="226" PARAM_ID="23" DIVISION_ID="F" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="227" PARAM_ID="23" DIVISION_ID="G" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="228" PARAM_ID="23" DIVISION_ID="H" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="229" PARAM_ID="23" DIVISION_ID="I" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="230" PARAM_ID="23" DIVISION_ID="Z" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="231" PARAM_ID="24" DIVISION_ID="A" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="232" PARAM_ID="24" DIVISION_ID="B" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="233" PARAM_ID="24" DIVISION_ID="C" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="234" PARAM_ID="24" DIVISION_ID="D" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="235" PARAM_ID="24" DIVISION_ID="E" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="236" PARAM_ID="24" DIVISION_ID="F" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="237" PARAM_ID="24" DIVISION_ID="G" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="238" PARAM_ID="24" DIVISION_ID="H" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="239" PARAM_ID="24" DIVISION_ID="I" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="240" PARAM_ID="24" DIVISION_ID="Z" VALUE="10" />
    <SENSITIVITY_PARAMETER ID="241" PARAM_ID="25" DIVISION_ID="A" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="242" PARAM_ID="25" DIVISION_ID="B" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="243" PARAM_ID="25" DIVISION_ID="C" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="244" PARAM_ID="25" DIVISION_ID="D" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="245" PARAM_ID="25" DIVISION_ID="E" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="246" PARAM_ID="25" DIVISION_ID="F" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="247" PARAM_ID="25" DIVISION_ID="G" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="248" PARAM_ID="25" DIVISION_ID="H" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="249" PARAM_ID="25" DIVISION_ID="I" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="250" PARAM_ID="25" DIVISION_ID="Z" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="251" PARAM_ID="26" DIVISION_ID="A" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="252" PARAM_ID="26" DIVISION_ID="B" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="253" PARAM_ID="26" DIVISION_ID="C" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="254" PARAM_ID="26" DIVISION_ID="D" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="255" PARAM_ID="26" DIVISION_ID="E" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="256" PARAM_ID="26" DIVISION_ID="F" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="257" PARAM_ID="26" DIVISION_ID="G" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="258" PARAM_ID="26" DIVISION_ID="H" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="259" PARAM_ID="26" DIVISION_ID="I" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="260" PARAM_ID="26" DIVISION_ID="Z" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="261" PARAM_ID="27" DIVISION_ID="A" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="262" PARAM_ID="27" DIVISION_ID="B" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="263" PARAM_ID="27" DIVISION_ID="C" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="264" PARAM_ID="27" DIVISION_ID="D" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="265" PARAM_ID="27" DIVISION_ID="E" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="266" PARAM_ID="27" DIVISION_ID="F" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="267" PARAM_ID="27" DIVISION_ID="G" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="268" PARAM_ID="27" DIVISION_ID="H" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="269" PARAM_ID="27" DIVISION_ID="I" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="270" PARAM_ID="27" DIVISION_ID="Z" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="271" PARAM_ID="28" DIVISION_ID="A" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="272" PARAM_ID="28" DIVISION_ID="B" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="273" PARAM_ID="28" DIVISION_ID="C" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="274" PARAM_ID="28" DIVISION_ID="D" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="275" PARAM_ID="28" DIVISION_ID="E" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="276" PARAM_ID="28" DIVISION_ID="F" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="277" PARAM_ID="28" DIVISION_ID="G" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="278" PARAM_ID="28" DIVISION_ID="H" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="279" PARAM_ID="28" DIVISION_ID="I" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="280" PARAM_ID="28" DIVISION_ID="Z" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="281" PARAM_ID="29" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="282" PARAM_ID="29" DIVISION_ID="B" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="283" PARAM_ID="29" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="284" PARAM_ID="29" DIVISION_ID="D" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="285" PARAM_ID="29" DIVISION_ID="E" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="286" PARAM_ID="29" DIVISION_ID="F" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="287" PARAM_ID="29" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="288" PARAM_ID="29" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="289" PARAM_ID="29" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="290" PARAM_ID="29" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="291" PARAM_ID="30" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="292" PARAM_ID="30" DIVISION_ID="B" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="293" PARAM_ID="30" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="294" PARAM_ID="30" DIVISION_ID="D" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="295" PARAM_ID="30" DIVISION_ID="E" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="296" PARAM_ID="30" DIVISION_ID="F" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="297" PARAM_ID="30" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="298" PARAM_ID="30" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="299" PARAM_ID="30" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="300" PARAM_ID="30" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="301" PARAM_ID="31" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="302" PARAM_ID="31" DIVISION_ID="B" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="303" PARAM_ID="31" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="304" PARAM_ID="31" DIVISION_ID="D" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="305" PARAM_ID="31" DIVISION_ID="E" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="306" PARAM_ID="31" DIVISION_ID="F" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="307" PARAM_ID="31" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="308" PARAM_ID="31" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="309" PARAM_ID="31" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="310" PARAM_ID="31" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="311" PARAM_ID="32" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="312" PARAM_ID="32" DIVISION_ID="B" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="313" PARAM_ID="32" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="314" PARAM_ID="32" DIVISION_ID="D" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="315" PARAM_ID="32" DIVISION_ID="E" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="316" PARAM_ID="32" DIVISION_ID="F" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="317" PARAM_ID="32" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="318" PARAM_ID="32" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="319" PARAM_ID="32" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="320" PARAM_ID="32" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="321" PARAM_ID="33" DIVISION_ID="A" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="322" PARAM_ID="33" DIVISION_ID="B" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="323" PARAM_ID="33" DIVISION_ID="C" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="324" PARAM_ID="33" DIVISION_ID="D" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="325" PARAM_ID="33" DIVISION_ID="E" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="326" PARAM_ID="33" DIVISION_ID="F" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="327" PARAM_ID="33" DIVISION_ID="G" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="328" PARAM_ID="33" DIVISION_ID="H" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="329" PARAM_ID="33" DIVISION_ID="I" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="330" PARAM_ID="33" DIVISION_ID="Z" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="331" PARAM_ID="34" DIVISION_ID="A" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="332" PARAM_ID="34" DIVISION_ID="B" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="333" PARAM_ID="34" DIVISION_ID="C" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="334" PARAM_ID="34" DIVISION_ID="D" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="335" PARAM_ID="34" DIVISION_ID="E" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="336" PARAM_ID="34" DIVISION_ID="F" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="337" PARAM_ID="34" DIVISION_ID="G" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="338" PARAM_ID="34" DIVISION_ID="H" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="339" PARAM_ID="34" DIVISION_ID="I" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="340" PARAM_ID="34" DIVISION_ID="Z" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="341" PARAM_ID="35" DIVISION_ID="A" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="342" PARAM_ID="35" DIVISION_ID="B" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="343" PARAM_ID="35" DIVISION_ID="C" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="344" PARAM_ID="35" DIVISION_ID="D" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="345" PARAM_ID="35" DIVISION_ID="E" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="346" PARAM_ID="35" DIVISION_ID="F" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="347" PARAM_ID="35" DIVISION_ID="G" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="348" PARAM_ID="35" DIVISION_ID="H" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="349" PARAM_ID="35" DIVISION_ID="I" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="350" PARAM_ID="35" DIVISION_ID="Z" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="351" PARAM_ID="36" DIVISION_ID="A" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="352" PARAM_ID="36" DIVISION_ID="B" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="353" PARAM_ID="36" DIVISION_ID="C" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="354" PARAM_ID="36" DIVISION_ID="D" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="355" PARAM_ID="36" DIVISION_ID="E" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="356" PARAM_ID="36" DIVISION_ID="F" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="357" PARAM_ID="36" DIVISION_ID="G" VALUE="0.5" />
    <SENSITIVITY_PARAMETER ID="358" PARAM_ID="36" DIVISION_ID="H" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="359" PARAM_ID="36" DIVISION_ID="I" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="360" PARAM_ID="36" DIVISION_ID="Z" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="361" PARAM_ID="37" DIVISION_ID="A" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="362" PARAM_ID="37" DIVISION_ID="B" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="363" PARAM_ID="37" DIVISION_ID="C" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="364" PARAM_ID="37" DIVISION_ID="D" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="365" PARAM_ID="37" DIVISION_ID="E" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="366" PARAM_ID="37" DIVISION_ID="F" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="367" PARAM_ID="37" DIVISION_ID="G" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="368" PARAM_ID="37" DIVISION_ID="H" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="369" PARAM_ID="37" DIVISION_ID="I" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="370" PARAM_ID="37" DIVISION_ID="Z" VALUE="2" />
    <SENSITIVITY_PARAMETER ID="371" PARAM_ID="38" DIVISION_ID="A" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="372" PARAM_ID="38" DIVISION_ID="B" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="373" PARAM_ID="38" DIVISION_ID="C" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="374" PARAM_ID="38" DIVISION_ID="D" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="375" PARAM_ID="38" DIVISION_ID="E" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="376" PARAM_ID="38" DIVISION_ID="F" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="377" PARAM_ID="38" DIVISION_ID="G" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="378" PARAM_ID="38" DIVISION_ID="H" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="379" PARAM_ID="38" DIVISION_ID="I" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="380" PARAM_ID="38" DIVISION_ID="Z" VALUE="0.1" />
    <SENSITIVITY_PARAMETER ID="381" PARAM_ID="39" DIVISION_ID="A" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="382" PARAM_ID="39" DIVISION_ID="B" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="383" PARAM_ID="39" DIVISION_ID="C" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="384" PARAM_ID="39" DIVISION_ID="D" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="385" PARAM_ID="39" DIVISION_ID="E" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="386" PARAM_ID="39" DIVISION_ID="F" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="387" PARAM_ID="39" DIVISION_ID="G" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="388" PARAM_ID="39" DIVISION_ID="H" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="389" PARAM_ID="39" DIVISION_ID="I" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="390" PARAM_ID="39" DIVISION_ID="Z" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="391" PARAM_ID="40" DIVISION_ID="A" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="392" PARAM_ID="40" DIVISION_ID="B" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="393" PARAM_ID="40" DIVISION_ID="C" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="394" PARAM_ID="40" DIVISION_ID="D" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="395" PARAM_ID="40" DIVISION_ID="E" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="396" PARAM_ID="40" DIVISION_ID="F" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="397" PARAM_ID="40" DIVISION_ID="G" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="398" PARAM_ID="40" DIVISION_ID="H" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="399" PARAM_ID="40" DIVISION_ID="I" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="400" PARAM_ID="40" DIVISION_ID="Z" VALUE="0.25" />
    <SENSITIVITY_PARAMETER ID="401" PARAM_ID="41" DIVISION_ID="A" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="402" PARAM_ID="41" DIVISION_ID="B" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="403" PARAM_ID="41" DIVISION_ID="C" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="404" PARAM_ID="41" DIVISION_ID="D" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="405" PARAM_ID="41" DIVISION_ID="E" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="406" PARAM_ID="41" DIVISION_ID="F" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="407" PARAM_ID="41" DIVISION_ID="G" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="408" PARAM_ID="41" DIVISION_ID="H" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="409" PARAM_ID="41" DIVISION_ID="I" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="410" PARAM_ID="41" DIVISION_ID="Z" VALUE="1" />
    <SENSITIVITY_PARAMETER ID="411" PARAM_ID="42" DIVISION_ID="A" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="412" PARAM_ID="42" DIVISION_ID="B" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="413" PARAM_ID="42" DIVISION_ID="C" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="414" PARAM_ID="42" DIVISION_ID="D" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="415" PARAM_ID="42" DIVISION_ID="E" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="416" PARAM_ID="42" DIVISION_ID="F" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="417" PARAM_ID="42" DIVISION_ID="G" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="418" PARAM_ID="42" DIVISION_ID="H" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="419" PARAM_ID="42" DIVISION_ID="I" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="420" PARAM_ID="42" DIVISION_ID="Z" VALUE="1.5" />
    <SENSITIVITY_PARAMETER ID="421" PARAM_ID="43" DIVISION_ID="A" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="422" PARAM_ID="43" DIVISION_ID="B" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="423" PARAM_ID="43" DIVISION_ID="C" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="424" PARAM_ID="43" DIVISION_ID="D" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="425" PARAM_ID="43" DIVISION_ID="E" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="426" PARAM_ID="43" DIVISION_ID="F" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="427" PARAM_ID="43" DIVISION_ID="G" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="428" PARAM_ID="43" DIVISION_ID="H" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="429" PARAM_ID="43" DIVISION_ID="I" VALUE="4" />
    <SENSITIVITY_PARAMETER ID="430" PARAM_ID="43" DIVISION_ID="Z" VALUE="4" />
  </SENSITIVITY_PARAMETERS>
  <CURRENCY_SETTINGS>
    <SOURCE_CURRENCY_CONSTANT_ID>3</SOURCE_CURRENCY_CONSTANT_ID>
    <TARGET_CURRENCY_CONSTANT_ID>4</TARGET_CURRENCY_CONSTANT_ID>
    <UP_CURRENCY_BASIS />
    <SOURCE_CURRENCY_REQUIREMENT>0</SOURCE_CURRENCY_REQUIREMENT>
    <SOURCE_CURRRENCY_DEFAULT />
  </CURRENCY_SETTINGS>
  <REQ_FIELDS />
  <PFPEXPORT_MAPPINGS />
  <PROJ_TYPE_HISTORY />
  <ROLLING_STMT_SETTINGS>
    <MULTIPLY_BS>False</MULTIPLY_BS>
    <SHOW_MULTIPLY_COLUMN>False</SHOW_MULTIPLY_COLUMN>
    <MULTIPLY_STATEMENTS>False</MULTIPLY_STATEMENTS>
    <RETAIN_PROJ_BS_BALANCES>True</RETAIN_PROJ_BS_BALANCES>
    <MULTIPLIER_IS_ACCT>False</MULTIPLIER_IS_ACCT>
    <MULTIPLIER>1</MULTIPLIER>
    <SUMMED_ITEMS>
      <SUMMED_ITEM TYPE="1" ID="30" />
    </SUMMED_ITEMS>
    <VALUE_ITEMS />
  </ROLLING_STMT_SETTINGS>
  <RMA_MAPPINGS />
  <RA_MAPPINGS />
  <RMA_CONDITIONS />
  <SYSTEM_RA_MAPPINGS />
  <ORG_MACROS />
</MODEL>